import { createElement } from '@/utils/dom.js';
import { formatGPA, formatShortDate } from '@/utils/formatters.js';
import { _badgeStyle, _gradeBarColor, _pseudoHash, _setCssVars } from './transcriptHelpers.js';

export const transcriptDocumentEndMethods = {
  _buildCertification(student, cgpa, honor, scale, semCount, stats) {
    const name = student.name || 'the above-named student';

    const statement = createElement(
      'p',
      { className: 'tv-cert-statement' },
      'This is to certify that ',
      createElement('strong', {}, name),
      ` has been formally assessed under the `,
      createElement('strong', {}, scale.label),
      ` grading system across `,
      createElement('strong', {}, `${semCount} academic semester${semCount !== 1 ? 's' : ''}`),
      `, accumulating `,
      createElement('strong', {}, `${stats.totalCU} credit units`),
      ` over `,
      createElement('strong', {}, `${stats.courseCount} registered courses`),
      '. The Cumulative Grade Point Average recorded is ',
      createElement('strong', {}, formatGPA(cgpa)),
      honor ? [' — classified as ', createElement('strong', {}, honor.label), '.'] : ['.']
    );

    // Scale legend
    const legendRows = createElement('div', { className: 'tv-scale-legend' });
    legendRows.append(
      createElement('p', { className: 'tv-scale-legend-title' }, 'Grading Scale Reference')
    );

    scale.grades.forEach(({ letter, points, minScore, maxScore, cssClass }) => {
      const col = _gradeBarColor(letter);
      legendRows.append(
        createElement(
          'div',
          { className: 'tv-scale-row' },
          _setCssVars(
            createElement('span', { className: `tv-scale-grade grade-badge ${cssClass}` }, letter),
            { '--tv-grade-color': col }
          ),
          createElement('span', { className: 'tv-scale-range' }, `${minScore}–${maxScore}`),
          createElement('span', { className: 'tv-scale-pts' }, `${points.toFixed(1)} pts`)
        )
      );
    });

    return createElement('div', { className: 'tv-cert-section' }, statement, legendRows);
  },

  _buildFooter(cgpa, honor, scale, semCount, stats) {
    const style = _badgeStyle(cgpa);

    const honorEl = honor
      ? _setCssVars(
          createElement(
            'span',
            { className: `tv-honor-badge tv-dynamic-badge ${honor.cssClass}` },
            createElement('span', { className: 'tv-honor-icon' }, honor.badge),
            honor.label
          ),
          {
            '--tv-accent-color': style.color,
            '--tv-accent-border': style.border,
            '--tv-accent-bg': style.bg,
          }
        )
      : null;

    const note = createElement(
      'p',
      { className: 'tv-footer-note' },
      `${semCount} semester${semCount !== 1 ? 's' : ''} · ${stats.totalCU} credit units · ${stats.courseCount} courses\n`,
      'This document is generated by GPA Pro for personal academic tracking.\n',
      'It does not constitute an official university transcript.'
    );

    return createElement(
      'div',
      { className: 'tv-doc-footer' },
      createElement(
        'div',
        { className: 'tv-footer-cgpa-group' },
        createElement('span', { className: 'tv-footer-cgpa-label' }, 'Cumulative GPA (CGPA)'),
        createElement('span', { className: 'tv-footer-cgpa-val' }, formatGPA(cgpa)),
        createElement('span', { className: 'tv-footer-cgpa-denom' }, `/ ${scale.maxGPA.toFixed(2)}`)
      ),
      createElement(
        'div',
        { className: 'tv-footer-sig-line' },
        createElement('div', { className: 'tv-footer-sig-blank' }),
        createElement('span', { className: 'tv-footer-sig-label' }, 'Academic Officer / Registrar')
      ),
      createElement('div', { className: 'tv-footer-honor' }, honorEl, note)
    );
  },

  _buildAuthStrip(student, cgpa) {
    const raw = `${student.name ?? ''}:${this._docId}:${formatGPA(cgpa)}`;
    const hash = _pseudoHash(raw);
    const date = formatShortDate(this._issuedAt);

    return createElement(
      'div',
      { className: 'tv-auth-strip', 'aria-hidden': 'true' },
      createElement(
        'span',
        { className: 'tv-auth-text' },
        `Issued ${date} · GPA Pro v2.0 · For personal use only`
      ),
      createElement('span', { className: 'tv-auth-hash' }, `DOC:${this._docId}·FP:${hash}`)
    );
  },

  _buildEmpty() {
    return createElement(
      'div',
      { className: 'tv-empty' },
      createElement('div', { className: 'tv-empty-icon' }, '📄'),
      createElement('h3', {}, 'No Academic Records Yet'),
      createElement(
        'p',
        {},
        'Add semesters and courses on the Dashboard to generate your transcript.'
      )
    );
  },
};
